# Site
repository: rosolko/rosolko.github.io
favicon: assets/icon.png

# Personal info
name: Aliaksandr Rasolka
title: Senior Backend Developer
email: rosolko@gmail.com

# Social links
twitter_username: arosolko
github_username:  rosolko
linkedin_username: rosolko

# About Section
about_content: |
  Hi, my name's Alex and I'm a Software Engineer and now seeking full-time Senior Node.js Backend Developer roles.
  Have 4+ years of experience in Backend Development.
  Have 5+ years experience in Test Automation of API, Web and Mobile applications.

  You can easily <a href="assets/cv.pdf" download>download</a> this CV as PDF or <a onclick="window.print()">print</a> it.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
