# Site
repository: rosolko/rosolko.github.io
favicon: assets/icon.png

# Content configuration version
version: 2

# Personal info
name: Aliaksandr Rasolka
title: Senior Backend Developer
email: rosolko@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: arosolko
github_username:  rosolko
linkedin_username: rosolko

# Additional icon links
additional_links:
  - title: medium
    icon: fab fa-medium
    url: https://medium.com/@rosolko

# About Section
about_title: Hi
about_content: |
  My name's Alex. 
  
  I'm a Software Engineer and now seeking full-time Senior Node.js Backend Developer roles.
  
  Have 4+ years of experience in Backend Development.
  
  Have 5+ years experience in Test Automation of API, Web and Mobile applications.

  You can easily <mark><a href="assets/cv.pdf" download>download</a></mark> my CV.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
